name: Bug report
description: Create a report 
labels: [bug]

body:
  - type: textarea
    id: description
    attributes:
      label: "Describe your issue"
    validations:
      required: true
  - type: input
    id: page_url
    attributes:
      label: "In what page/URL does it happen?"
      placeholder: "https://google.com/results?index=1"
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
    validations:
      required: true
  - type: textarea
    id: screens
    attributes:
      label: Please provide screenshots if applicable
    validations:
      required: false
