name: Bug report
description: Create a report 
labels: [bug]

body:
  - type: textarea
    id: desc
    attributes:
      label: "Describe your issue"
      placeholder: "Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat."
    validations:
      required: true
  - type: input
    id: page_url
    attributes:
      label: "In what page/URL does it happen?"
      placeholder: "https://google.com/results?index=1"
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: screens
    attributes:
      label: Please provide screenshots
      placeholder: Please provide screenshots if applicable
    validations:
      required: false
